### ISSUE TITLE
Ссылки на учебники

### ISSUE THREAD

**Issue by Hoodie-Huuuuu** [dmitrylala/gos#22]
Яндекс диск с учебниками переехал, поэтому полно битых ссылок. Надо их перезабить

**Comment by dmitrylala** [comment]
@Hoodie-Huuuuu займешься?

**Comment by Hoodie-Huuuuu** [comment]
> @Hoodie-Huuuuu займешься?

ок

**Comment by Hoodie-Huuuuu** [comment]
#35
